apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: test-flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: ghcr.io/stefanprodan/podinfo:6.8.0
          ports:
            - containerPort: 9898
